#!/usr/bin/ env bash

# Check if an argument is provided
if [ $# -eq 0 ]; then
   echo "Please provide a username as an argument."
   exit 1
fi

# Assign the argument to a variable
username=$1

# Run the 'whoami' command under the specified user
sudo -u $username whoami
